### PR TITLE
feat: bump release level to production/stable

### LINKED ISSUE #145: Release as GA
[GA release template](https://github.com/googleapis/google-cloud-common/issues/287)
## Required 

- [ ] 28 days elapsed since last beta release with new API surface
- [x] Server API is GA
- [x] Package API is stable, and we can commit to backward compatibility
- [x] All dependencies are GA

### PR DESCRIPTION
**Pull request by parthea**
Fixes #145 🦕

### CODE REVIEW

**Comment by meredithslota** [comment]
There are a couple of open issues that need to be resolved before this gets merged, I think (open to discussion). What are your thoughts on making sure the other PRs get merged first?

**Comment by parthea** [comment]
SGTM

**Comment by anguillanneuf** [comment]
The Python client for Lite should be ready for GA now. The only one we're still unsure about Lite is its Java client.

**Comment by parthea** [comment]
Wait for https://github.com/googleapis/python-pubsublite/pull/171

**Comment by parthea** [comment]
Wait for #173

**Review by anguillanneuf — APPROVED** [review]

**Review by manuelmenzella-google — APPROVED** [review]

**Pull request merged**
